export { default as Home } from './Home';
export { default as HotMovies } from './HotMovies';
export { default as Movies } from './Movies';
export { default as NewMovies } from './NewMovies';
export { default as SeriesMovie } from './SeriesMovie';
export { default as ShowDetail } from './ShowDetail';
export { default as MovieDetail } from './MovieDetail';
export { default as FAQ } from './FAQ';
export { default as Search } from './Search';
